/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int t = in.nextInt();
        for(int a0 = 0; a0 < t; a0++){
            long n = in.nextLong();
            long result=0;
            result = fibo(n);
            System.out.println(result);
        }
    }
    
    static long fibo(long n){
        long f1 = 1,f2 = 2,f = 0, sum = 0;
        while(f1 < n){
            if(f1 % 2 == 0){
                sum += f1;
            }
            f = f1 + f2;
            f1 = f2;
            f2 = f;
        }
        return sum;
    } 
    
}